### ISSUE TITLE
Do you think you could continue matrix-static?

### ISSUE THREAD

**Issue by bkil** [t3chguy/matrix-appservice-messenger#3]
Sorry to bother you in this unrelated repository. It is totally fine if you decline, but I'm just wondering whether you could give it a second chance? As a plot twist, the Matrix Archive (also renamed to Matrix Viewer) has been discontinued as just mentioned on their web page:

https://archive.matrix.org/
https://github.com/matrix-org/matrix-viewer

This invalidates the following issue, so again matrix-static is the only choice for those who want to preview a room without registering an account and installing a client:
https://github.com/matrix-org/matrix-static/issues/115

**Comment by t3chguy** [comment]
Its a project owned by matrix-org - not myself, I suggest raising a discussion somewhere else.
